## YAML Template.
---
plugins:
    -
        name: sample
        directory: bower_components/kbase-ui-plugin-sample/src/plugin
    -
        eg_plugin
    -
        about
    -
        databrowser
    -
        userprofile
    -
        narrativestore
    -
        dashboard
    -
        dataview
    -
        contact
    -
        typebrowser
navbar:
    menu:
        available_items:
            search: 
                path: search/?q=*
                label: Search Data
                icon: search
            narrative: 
                uri: funtional_site#narrativemanager/start
                label: Narrative
                icon: file
            narrativeTutorial: 
                uri: https://kbase.us/narrative-guide
                label: Narrative Tutorial
                icon: info-circle

            about_kbase: 
                uri: https://kbase.us/about
                label: About KBase
                icon: info-circle
            test: 
                path: test
                label: Testing Panel
                icon: flask
        menus:
            authenticated: [search, narrative, test, divider, divider]                
            unauthenticated: [about, divider, about_kbase, contact_us]
        