language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
branches:
  only:
    - develop
    - staging
    - master
    - ease-dev-campaign
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
install:
  - bower install
  - npm install
script: grunt build-config && grunt test